/**
 * Simple XMLHttpRequest to fetch list of deployments from home.html
 * A list of deployed projects is dynamically generated by server when we access home page
 */
const xmlHttp = new XMLHttpRequest();

xmlHttp.onreadystatechange = () => {
    if (xmlHttp.readyState === 4 && xmlHttp.status === 200) {
        document.querySelector(".deployments-section .list").innerHTML = xmlHttp.responseText;
    }
};

xmlHttp.open("GET", "artifacts/deployments.html", true);
xmlHttp.send(null);
