/**
 * Simple XMLHttpRequest to fetch list of examples from examples.html
 * Example list is dynamically generated by server when we access home page
 */
var xmlHttp = new XMLHttpRequest();

xmlHttp.onreadystatechange = () => {
    if (xmlHttp.readyState == 4 && xmlHttp.status == 200) {
        document.querySelector(".examples-section .list").innerHTML = xmlHttp.responseText;
    }
};

xmlHttp.open("GET", "artifacts/examples.html", true);
xmlHttp.send(null);
